# Generated by Django 5.0 on 2024-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user_bank_account',
        ),
    ]
