# Generated by Django 5.0 on 2024-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
